services:
  - type: web
    name: car-rental-api
    env: docker
    repo: https://github.com/ayechanaungdev/full-stack-development
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: PORT
        value: 3000
