services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    restart: unless-stopped
